language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
dist: bionic
sudo: true

matrix:
  fast_finish: true

install:
  - pip install tox-travis
  - pip install -r test-requirements.txt
  - pip install .

script:
  - tox -e pep8
  - tox

after_success:
  - codecov
