pipeline {
    agent none
    triggers {
        cron('H 4 * * *')
    }
    environment {
        IPMI=credentials('IPMI')
        IPMI_USERNAME="${env.IPMI_USR}"
        IPMI_PASSWORD="${env.IPMI_PSW}"
        IPMI_DNS_ZONE='mgmt.name.com'
        MAAS_URL='https://maas.url'
        MAAS_API_KEY=credentials('MAAS_API_KEY')
        NETBOX_URL='https://netbox.url'
        NETBOX_TOKEN=credentials('NETBOX_TOKEN')
        NETBOX_DEVICE_IDS='123,456'
        SITE='dc_name'
    }
    stages {
        stage('Daily NetBox Validation') {
            parallel {
                stage('serialnumber-check') {
                    agent {
                        label 'maas2netbox-worker'
                    }
                    steps {
                        sh 'maas2netbox -c validate --log INFO -f serialnumber'
                    }
                }
                stage('ipmi-location-check') {
                    agent {
                        label 'maas2netbox-worker'
                    }
                    steps {
                        sh 'maas2netbox -c validate --log INFO -f ipmi_location'
                    }
                }
                stage('ipmi-interface-check') {
                    agent {
                        label 'maas2netbox-worker'
                    }
                    steps {
                        sh 'maas2netbox -c validate --log INFO -f ipmi_interface'
                    }
                }
                stage('status-check') {
                    agent {
                        label 'maas2netbox-worker'
                    }
                    steps {
                        sh 'maas2netbox -c validate --log INFO -f status'
                    }
                }
                stage('primaryIPv4-check') {
                    agent {
                        label 'maas2netbox-worker'
                    }
                    steps {
                        sh 'maas2netbox -c validate --log INFO -f primaryIPv4'
                    }
                }
                stage('interfaces-check') {
                    agent {
                        label 'maas2netbox-worker'
                    }
                    steps {
                        sh 'maas2netbox -c validate --log INFO -f interfaces'
                    }
                }
                stage('platform-check') {
                    agent {
                        label 'maas2netbox-worker'
                    }
                    steps {
                        sh 'maas2netbox -c validate --log INFO -f platform'
                    }
                }
                stage('switch-connections-check') {
                    agent {
                        label 'maas2netbox-worker'
                    }
                    steps {
                        sh 'maas2netbox -c validate --log INFO -f switch_connections'
                    }
                }
            }
        }
    }
}
